{% set version = '0.1.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pryr
  version: {{ version|replace("-", "_") }}

source:
  fn: pryr_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/pryr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/pryr/pryr_{{ version }}.tar.gz
  sha256: 6acd88341dde4fe247a5cafd3949b281dc6742b7d60f68b57c1feb84b96739ac


  # patches:
   # List any patch files here
   # - fix.patch

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0


  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 0.8.0)
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make

  host:
    - r-base
    - r-rcpp >=0.11.0
    - r-codetools
    - r-stringr

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.11.0
    - r-codetools
    - r-stringr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pryr')"           # [not win]
    - "\"%R%\" -e \"library('pryr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/hadley/pryr
  license: GPL-2
  summary: Useful tools to pry back the covers of R and understand the language at a deeper level.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: pryr
# Version: 0.1.3
# Title: Tools for Computing on the Language
# Description: Useful tools to pry back the covers of R and understand the language at a deeper level.
# Authors@R: c( person("Hadley", "Wickham", ,"hadley@rstudio.com", c("aut", "cre")), person("R Core team", role = "ctb", comment = "Some code extracted from base R") )
# License: GPL-2
# URL: https://github.com/hadley/pryr
# BugReports: https://github.com/hadley/pryr/issues
# LinkingTo: Rcpp
# Depends: R (>= 3.1.0)
# Imports: stringr, codetools, methods, Rcpp (>= 0.11.0)
# Suggests: testthat (>= 0.8.0)
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-10-30 15:32:57 UTC; lionel
# Author: Hadley Wickham [aut, cre], R Core team [ctb] (Some code extracted from base R)
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-10-30 15:34:16 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
