travis:
  secure:
    BINSTAR_TOKEN: qbnfyTGVlbdepkp/he4d3LdboY+nLGxAJkZwq0JPHj+3WwR3Iad62lVe3r39xtZWMx8pfX1/e5cVMUpMvuO9FjPtkCWywXEuCcqmZClg8+l1ZKMIfHFZfJVA/bwHYlRqJOPuhepVCnEooYes4FG5dorogzkOWoNgYwaWEn3IgF53NNiYsApS5DuEzptBFXmBLGBr/DbB4oKC9E2qaS0/6G1dUC3uPcL7epB6hRRdNZFYHskHCQGp8nijotSoukYQ44M9d6ZKk+H530qJ4VxNLWBo21llqDNE23lMBoJ6zAWAq7a1CrHi43qsqa+haHUZXapEkHp2TZ/QGcvaAp82VgbX2cVFreWfTcvf/kFcZNr59739674QHTY0VU9vXg79Oj8EiWoL41M/EiuN+B/jlpDY3MYQ1ZjphgLfY1ENCaFPFNJdx6yQFBtzUfCiZnepmNEtIJc3aN7LgOJsGZM+XSJJP8j+2zu3BvM7ee5QDYLVHL/LTsCRlAG4kYyQgi0phqcV5XgllYZvGi3UJtsx2IJ8RIE0AelZMUFRcG+N+rg8/P8pJu+y8/9DFqRArEs6fGl8J9CrZyBUISvYwPrAw3cau20kJ7l5PBnm3VblkOmcE+XXHuPjnVVgo+Ic0pSVYJ72lBjvn/4WwEGjQLR81mGIPhRp1kgIrjxaaDIh9NY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
