travis:
  secure:
    BINSTAR_TOKEN: bfxTfxW9yX5y0gKd1CRo61FGP8nscXpPmKoVzuPAii91tFATBKo7gnZEUPcvN+DFUC1JlWgnF9u4Y343Rd9Lxwwm6jM1dPuahLyrjpda12BsXya2u6W/jSJ5pDOAEKaBtcmJwSWE19zlVhwYKELSxoUfDoKhtFkwXP8TUc+BmipDGcFwDkvBqP04hf+OUJHrCgY5Mpf7xt83doCdEOvbA2G+n+P/9mVgaViBAefulWzyAATnKZL4I93bTb4YUwln11fCYq0TYK8rqYaP/Z71JN5AG6Q+t61oKc2TtJPTHl/nTS2fP9HI7Gv67npHQNAHnd2DIuGyW2QCaAEcqllh9Q6g5fmooG46AxXcx2CkEMCDWS4+aA+ELzta4UPH8AH9BpPWEE202WNy4FnRmm/Lcmbwy956nWn8H9LlFb7MvvGfQqVmQr26A0MRb+gs4utYPMeMSiMJT/dKryTAhrKxfvUsY0erbxIx970hbKHJjmb32c2MOdXmK7K+HXeuwEgzDjEC7gHp0U9Z59F1VwY7DLEO9W1vw2iQyvzX7hqC0WnH4oENGSoxQ/FMxXhOfeWrKfhEY3/aIo5OxKVNvkvfGAQPaaY9VirDQjXVROWGSVkiUFiLsBO/3t1w+qeLsCbbJz12XWfr3VvHiorLBq1InUd6vroZAznfJ5tMTUVC3Xc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
