travis:
  secure:
    BINSTAR_TOKEN: mQyS6JAhjbdrge30g4vH7SJyFnAQyY7/53Ve2Q6DY+eGor4mtQnNfA84ne0pqLOMS5dliA1Y5HD1B9bjNFekzF/uab9GtXJG6PWgM9w/etm078zQGCRpKTo3Tr6wa3AMALRpK7LVBUfNhtPM/25MsmfMZ0EQGId0gpw5yOlI6YuOVMu22zBXJUOfZEjYFvkOKcqKLeuFDFI/v0z+SFwI1jT+6R3OBeJ9cMcMkIZiGoui2gjHvFuJFyP0qyYIscVfivVxAqu+1f48qGRxHdTr0TkCNNSSnm4t7/AlYgLFcHn8R6z6yPdeuJYAw7hZUOJdX200ioeDp5WdKyz/GwXcDk+XN3h3RlVQE9s2Qb6wpflVBoKvcnc2jYhSt9JUsRgX0OhorAC7thhaGHAL5WUsya94zGwzde6kRvDuFKozQFpM1VJEWZR5Jx2vyHXuy0ojwx382mDYceEyUkQSRmiD9D7wfHktAph/Br3xr1yVrCfVwxJSdkjyck9AFuxXg15Vz1WZOTIGLo0ErelwFVjGYT25HpM7qipGYZ8Q/aoxqqyah7OExAhpDyXKppxrkfwjX3PQ75Osuj58qK09Lv8syj6YnR4+oEYwb05MBY3ywHk5SSNwBSf4e+N7mLSKIiLXyiUYgSvp4MSLSBKZl44DxyUodyF97j19sAUNYO0ETuY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
